version: "3.9"
volumes:
  data_api:
  MongoOFVp:
networks:
  ofvp_project:
    name: ofvpNetwork

services:
  mongo:
    image: mongo
    restart: on-failure
    hostname: mongo_container.local
    volumes:
      - MongoOFVp:/data/db
    command: "--quiet --port 27017 --nounixsocket --bind_ip_all --noauth"
    ports:
      - 27017:27017/tcp
  daemon:
    restart: on-failure
    image: ghcr.io/ofvp-project/deamonmaneger:next
    hostname: ofvp-daemon.local
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongo"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data
    depends_on:
      - mongo
    links:
      - "mongo"

  wireguard:
    restart: on-failure
    privileged: true
    build:
      dockerfile: Dockerfile
    environment:
      DAEMON_HOST: "http://daemon:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    volumes:
      - /lib/modules/:/lib/modules/:ro
    ports:
      - 51820:51820/udp
    depends_on:
      - daemon
    links:
      - "daemon"