version: "3.9"
volumes:
  data_api:
  MongoOFVp:
networks:
  ofvp_project:

services:
  db:
    restart: on-failure
    image: mongo
    volumes:
      - MongoOFVp:/data/db
    command:
      - "--bind_ip_all"
      - "--quiet"
      - "--logpath"
      - "/dev/null"
    networks:
      - ofvp_project
    ports:
      - 27017:27017/tcp
  ofvp_daemon_maneger:
    container_name: ofvp_daemon_maneger
    restart: on-failure
    image: ghcr.io/ofvp-project/deamonmaneger:latest
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://db"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data
    networks:
      - ofvp_project

  ofvp_wireguard:
    container_name: ofvp_wireguard
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://db"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    volumes:
      - /lib/modules/:/lib/modules/:ro
    ports:
      - 51820:51820/udp
    networks:
      - ofvp_project