version: "3.9"
volumes:
  data_api:
  MongoOFVp:
networks:
  ofvp_network:
services:
  ofvp_mongodb:
    container_name: ofvp_mongodb
    restart: on-failure
    image: mongo
    volumes:
      - MongoOFVp:/data/db
    networks:
      - "ofvp_network"
    environment:
      - PUID=1000
      - PGID=1000
    entrypoint:
    - "mongod"
    - "--bind_ip_all"
    - "--quiet"
    - "--logpath"
    - "/dev/null"

  ofvp_daemon_maneger:
    container_name: ofvp_daemon_maneger
    restart: on-failure
    image: ghcr.io/ofvp-project/deamonmaneger:latest
    depends_on:
      - ofvp_mongodb
    networks:
      - "ofvp_network"
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://ofvp_mongodb:27017"
      COOKIE_SECRET: "dev"
      PASSWORD_ENCRYPT: "dev"
      DAEMON_PASSWORD: "dev"
      DAEMON_USER: "dev"
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data

  ofvp_wireguard:
    container_name: ofvp_wireguard
    restart: on-failure
    image: ghcr.io/ofvp-project/wireguard:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - "ofvp_network"
    environment:
      DAEMON_HOST: "http://ofvp_daemon_maneger:5000"
      DAEMON_PASSWORD: "dev"
      DAEMON_USER: "dev"
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    volumes:
      - /lib/modules/:/lib/modules/:ro
    ports:
      - 51820:51820/udp
    depends_on:
      - ofvp_daemon_maneger