name: Publish latest image
on:
  push:
    branches:
      - main

env:
  DOCKERPLATFORM: "linux/amd64,linux/arm64,linux/s390x"
  DOCKERIMAGE: "ghcr.io/ofvp-project/wireguard"

jobs:
  latestDeploy:
    runs-on: ubuntu-latest
    name: Publish latest
    environment:
      name: Docker_Latest
      url: "ghcr.io/ofvp-project/wireguard"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: server
          tags: "${{ env.DOCKERIMAGE }}:latest"
          platforms: ${{ env.DOCKERPLATFORM }}
          cache-from: type=gha,scope=${{ github.ref }}_${{ hashFiles('**/package-lock.json') }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_${{ hashFiles('**/package-lock.json') }}
