name: Publish latest image
on:
  push:
    branches:
      - main

jobs:
  latestDeploy:
    runs-on: ubuntu-latest
    name: Publish latest
    environment:
      name: Docker_Latest
      url: "ghcr.io/ofvp-project/wireguard"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: server
          tags: "ghcr.io/ofvp-project/wireguard:latest"
          platforms: "linux/amd64,linux/arm64"
          cache-from: type=gha,scope=${{ hashFiles('**/package-lock.json') }}
          cache-to: type=gha,mode=max,scope=${{ hashFiles('**/package-lock.json') }}
